"""Loading, generating and overriding YAML config files."""
from __future__ import annotations

import argparse
from pathlib import Path

import pytest

from haemolynx.parsers import (
    ConfigError,
    Schema,
    Setting,
    add_schema_arguments,
    cli_overrides,
    dump_config,
    load_config,
    settings_for,
)

yaml = pytest.importorskip("yaml")


def _schema() -> Schema:
    return Schema(
        [
            Setting("input_path", "path", "in.tif", "Mask to analyse", "Input"),
            Setting(
                "voxel_size_um", "float", 1.0, "Voxel edge length", "Input",
                unit="um", minimum=0.0,
            ),
            Setting("use_masks", "bool", False, "Assign boundaries from masks", "Boundaries"),
            Setting(
                "mask_path", "path", None, "Arteriole mask", "Boundaries",
                requires=("use_masks",),
            ),
            Setting(
                "mode", "choice", "fast", "Statistics detail", "Output",
                choices=("fast", "full"),
            ),
            Setting("diameters", "mapping", {"B01": 5.0}, "Diameter per order", "Output"),
        ],
        title="Test config",
        description="Generated by the test",
    )


def _write(tmp_path: Path, text: str) -> Path:
    path = tmp_path / "config.yaml"
    path.write_text(text, encoding="utf-8")
    return path


# --- loading ---------------------------------------------------------------


def test_a_config_need_only_state_what_it_changes(tmp_path):
    path = _write(tmp_path, "output:\n  mode: full\n")
    settings = load_config(path, _schema())
    assert settings["mode"] == "full"
    assert settings["voxel_size_um"] == 1.0  # untouched default
    assert set(settings) == set(_schema().names)


def test_flat_and_sectioned_layouts_both_load(tmp_path):
    sectioned = load_config(_write(tmp_path, "input:\n  voxel_size_um: 3\n"), _schema())
    flat = load_config(_write(tmp_path, "voxel_size_um: 3\n"), _schema())
    assert sectioned == flat


def test_an_empty_config_is_all_defaults(tmp_path):
    assert load_config(_write(tmp_path, ""), _schema()) == _schema().validate({})


def test_a_missing_config_file_says_so(tmp_path):
    with pytest.raises(ConfigError, match="Config file not found"):
        load_config(tmp_path / "absent.yaml", _schema())


def test_a_config_that_is_not_a_mapping_is_rejected(tmp_path):
    with pytest.raises(ConfigError, match="must contain a mapping"):
        load_config(_write(tmp_path, "- one\n- two\n"), _schema())


def test_load_errors_name_the_offending_file(tmp_path):
    path = _write(tmp_path, "output:\n  mode: medium\n")
    with pytest.raises(ConfigError) as excinfo:
        load_config(path, _schema())
    assert "config.yaml" in str(excinfo.value)
    assert "allowed values" in str(excinfo.value)


def test_a_setting_repeated_in_two_sections_is_rejected(tmp_path):
    path = _write(tmp_path, "input:\n  mode: fast\noutput:\n  mode: full\n")
    with pytest.raises(ConfigError, match="appears more than once"):
        load_config(path, _schema())


def test_overrides_win_over_the_file(tmp_path):
    path = _write(tmp_path, "output:\n  mode: full\n")
    settings = load_config(path, _schema(), overrides={"mode": "fast"})
    assert settings["mode"] == "fast"


def test_overrides_are_validated_like_everything_else(tmp_path):
    path = _write(tmp_path, "")
    with pytest.raises(ConfigError, match="allowed values are"):
        load_config(path, _schema(), overrides={"mode": "medium"})


# --- generating ------------------------------------------------------------


def test_a_generated_config_round_trips_to_the_defaults(tmp_path):
    schema = _schema()
    path = dump_config(tmp_path / "generated.yaml", schema)
    assert load_config(path, schema) == schema.validate({})


def test_a_generated_config_documents_every_setting(tmp_path):
    schema = _schema()
    text = dump_config(tmp_path / "generated.yaml", schema).read_text(encoding="utf-8")
    for setting in schema:
        assert f"{setting.name}:" in text, f"{setting.name} missing from generated config"
        assert setting.help in text, f"{setting.name} help missing from generated config"


def test_a_generated_config_records_units_choices_and_prerequisites(tmp_path):
    text = dump_config(tmp_path / "generated.yaml", _schema()).read_text(encoding="utf-8")
    assert "[um; range 0.0..]" in text
    assert "one of: fast, full" in text
    assert "needs use_masks" in text


def test_generating_with_values_writes_those_values(tmp_path):
    schema = _schema()
    path = dump_config(tmp_path / "generated.yaml", schema, values={"mode": "full"})
    assert load_config(path, schema)["mode"] == "full"


def test_generating_validates_the_values_it_is_given(tmp_path):
    with pytest.raises(ConfigError, match="allowed values are"):
        dump_config(tmp_path / "generated.yaml", _schema(), values={"mode": "medium"})


def test_a_generated_config_is_valid_yaml(tmp_path):
    text = dump_config(tmp_path / "generated.yaml", _schema()).read_text(encoding="utf-8")
    loaded = yaml.safe_load(text)
    assert loaded["output"]["diameters"] == {"B01": 5.0}


# --- paths are written the same way on every platform ----------------------
#
# A `path` setting was serialised with `str(Path(...))`, which is the platform's
# own separator, so the committed configs -- generated on Linux, with forward
# slashes -- were rewritten wholesale the first time anyone ran
# `examples/regenerate_configs.py` on Windows, and that rewrite then broke the
# generator's own test back on Linux. Regenerating has to be platform-neutral.


def test_a_path_setting_is_written_with_forward_slashes(tmp_path):
    text = dump_config(
        tmp_path / "generated.yaml",
        _schema(),
        values={"input_path": Path("examples") / "images" / "brain.tiff"},
    ).read_text(encoding="utf-8")

    assert "examples/images/brain.tiff" in text
    assert "\\" not in text


def test_a_path_written_with_forward_slashes_reads_back_as_the_same_path(tmp_path):
    """Windows accepts forward slashes, so nothing is lost by writing them."""
    original = Path("examples") / "images" / "brain.tiff"
    path = dump_config(
        tmp_path / "generated.yaml", _schema(), values={"input_path": original}
    )
    assert load_config(path, _schema())["input_path"] == original


def test_regenerating_a_config_reproduces_it_byte_for_byte(tmp_path):
    """The property the committed configs need: generating twice is a no-op."""
    schema = _schema()
    values = {"input_path": Path("examples") / "images" / "brain.tiff"}
    first = dump_config(tmp_path / "first.yaml", schema, values=values)
    second = dump_config(
        tmp_path / "second.yaml", schema, values=load_config(first, schema)
    )
    assert second.read_text(encoding="utf-8") == first.read_text(encoding="utf-8")


def test_an_absolute_path_keeps_its_drive_and_root(tmp_path):
    """`C:/Users/...` is a valid Windows path; `C:Users/...` would not be."""
    absolute = Path(tmp_path) / "images" / "brain.tiff"
    path = dump_config(
        tmp_path / "generated.yaml", _schema(), values={"input_path": absolute}
    )
    written = yaml.safe_load(path.read_text(encoding="utf-8"))["input"]["input_path"]

    assert "\\" not in written
    assert written == absolute.as_posix()
    assert Path(written) == absolute
    assert Path(written).is_absolute()


def test_a_long_path_with_spaces_round_trips_through_dump_and_load(tmp_path):
    """Napari save/load on Windows used to corrupt paths that contain spaces.

    magicgui's FileEdit absolutises every path. A typical Dropbox / user-data
    path is far longer than PyYAML's default dump width, and when that path
    also contains a space the dumper folded it onto a second indented line.
    The hand-built config then contained invalid YAML, so "Save config..."
    appeared to succeed and "Load config..." failed on the file just written.
    """
    absolute = (
        tmp_path
        / "Dropbox"
        / (
            "Composite_06082026_E14p5_clnd5_25x_940nm_1040_texasred3kkda_"
            "zstack_spot1_1p5z_MCAregion_Simple Segmentation_arteriole.tiff"
        )
    )
    absolute.parent.mkdir(parents=True, exist_ok=True)
    absolute.write_bytes(b"")

    path = dump_config(
        tmp_path / "generated.yaml", _schema(), values={"input_path": absolute}
    )
    text = path.read_text(encoding="utf-8")

    assert "\n  Segmentation_arteriole.tiff" not in text
    assert "\\" not in text
    # One line, full path — wrapping at the space was the Windows bug.
    assert f"input_path: {absolute.as_posix()}" in text

    loaded = load_config(path, _schema())["input_path"]
    assert loaded == absolute
    assert Path(loaded).is_absolute()


def test_a_long_path_with_spaces_survives_a_gui_style_save_reload(tmp_path):
    """The full dump -> load cycle the panel uses must not rewrite the path."""
    absolute = (
        tmp_path
        / "My Dataset"
        / ("x" * 80)
        / "large arteriole mask.tiff"
    )
    schema = _schema()
    saved = dump_config(
        tmp_path / "panel_save.yaml", schema, values={"input_path": absolute}
    )
    # Re-parse the file bytes the way a later "Load config..." does.
    assert yaml.safe_load(saved.read_text(encoding="utf-8")) is not None
    assert load_config(saved, schema)["input_path"] == absolute


# --- command line ----------------------------------------------------------


def test_cli_flags_are_generated_from_the_schema():
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    parsed = parser.parse_args(["--voxel-size-um", "4", "--mode", "full"])
    assert cli_overrides(parsed) == {"voxel_size_um": "4", "mode": "full"}


def test_flags_not_given_are_absent_rather_than_defaulted():
    """"Not supplied" must stay distinguishable from "supplied the default"."""
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    assert cli_overrides(parser.parse_args([])) == {}


def test_choice_flags_reject_values_outside_the_schema(capsys):
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    with pytest.raises(SystemExit):
        parser.parse_args(["--mode", "medium"])


def test_bool_flags_take_an_explicit_true_or_false():
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    assert cli_overrides(parser.parse_args(["--use-masks", "true"]))["use_masks"] is True
    assert cli_overrides(parser.parse_args(["--use-masks", "no"]))["use_masks"] is False


def test_cli_overrides_flow_through_load_config(tmp_path):
    path = _write(tmp_path, "output:\n  mode: full\n")
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    parsed = parser.parse_args(["--mode", "fast", "--voxel-size-um", "2.5"])
    settings = load_config(path, _schema(), overrides=cli_overrides(parsed))
    assert settings["mode"] == "fast"
    assert settings["voxel_size_um"] == 2.5


# --- handing settings to a function ----------------------------------------


def test_settings_for_selects_the_named_subset():
    settings = _schema().validate({})
    assert settings_for(settings, ["mode", "use_masks"]) == {
        "mode": "fast",
        "use_masks": False,
    }


def test_settings_for_reports_names_that_are_not_present():
    with pytest.raises(ConfigError, match="Settings not present: nope"):
        settings_for(_schema().validate({}), ["mode", "nope"])
