"""Loading, generating and overriding YAML config files."""
from __future__ import annotations

import argparse
from pathlib import Path

import pytest

from ImageLynx.parsers import (
    ConfigError,
    Schema,
    Setting,
    add_schema_arguments,
    cli_overrides,
    dump_config,
    load_config,
    settings_for,
)

yaml = pytest.importorskip("yaml")


def _schema() -> Schema:
    return Schema(
        [
            Setting("input_path", "path", "in.tif", "Mask to analyse", "Input"),
            Setting(
                "voxel_size_um", "float", 1.0, "Voxel edge length", "Input",
                unit="um", minimum=0.0,
            ),
            Setting("use_masks", "bool", False, "Assign boundaries from masks", "Boundaries"),
            Setting(
                "mask_path", "path", None, "Arteriole mask", "Boundaries",
                requires=("use_masks",),
            ),
            Setting(
                "mode", "choice", "fast", "Statistics detail", "Output",
                choices=("fast", "full"),
            ),
            Setting("diameters", "mapping", {"B01": 5.0}, "Diameter per order", "Output"),
        ],
        title="Test config",
        description="Generated by the test",
    )


def _write(tmp_path: Path, text: str) -> Path:
    path = tmp_path / "config.yaml"
    path.write_text(text, encoding="utf-8")
    return path


# --- loading ---------------------------------------------------------------


def test_a_config_need_only_state_what_it_changes(tmp_path):
    path = _write(tmp_path, "output:\n  mode: full\n")
    settings = load_config(path, _schema())
    assert settings["mode"] == "full"
    assert settings["voxel_size_um"] == 1.0  # untouched default
    assert set(settings) == set(_schema().names)


def test_flat_and_sectioned_layouts_both_load(tmp_path):
    sectioned = load_config(_write(tmp_path, "input:\n  voxel_size_um: 3\n"), _schema())
    flat = load_config(_write(tmp_path, "voxel_size_um: 3\n"), _schema())
    assert sectioned == flat


def test_an_empty_config_is_all_defaults(tmp_path):
    assert load_config(_write(tmp_path, ""), _schema()) == _schema().validate({})


def test_a_missing_config_file_says_so(tmp_path):
    with pytest.raises(ConfigError, match="Config file not found"):
        load_config(tmp_path / "absent.yaml", _schema())


def test_a_config_that_is_not_a_mapping_is_rejected(tmp_path):
    with pytest.raises(ConfigError, match="must contain a mapping"):
        load_config(_write(tmp_path, "- one\n- two\n"), _schema())


def test_load_errors_name_the_offending_file(tmp_path):
    path = _write(tmp_path, "output:\n  mode: medium\n")
    with pytest.raises(ConfigError) as excinfo:
        load_config(path, _schema())
    assert "config.yaml" in str(excinfo.value)
    assert "allowed values" in str(excinfo.value)


def test_a_setting_repeated_in_two_sections_is_rejected(tmp_path):
    path = _write(tmp_path, "input:\n  mode: fast\noutput:\n  mode: full\n")
    with pytest.raises(ConfigError, match="appears more than once"):
        load_config(path, _schema())


def test_overrides_win_over_the_file(tmp_path):
    path = _write(tmp_path, "output:\n  mode: full\n")
    settings = load_config(path, _schema(), overrides={"mode": "fast"})
    assert settings["mode"] == "fast"


def test_overrides_are_validated_like_everything_else(tmp_path):
    path = _write(tmp_path, "")
    with pytest.raises(ConfigError, match="allowed values are"):
        load_config(path, _schema(), overrides={"mode": "medium"})


# --- generating ------------------------------------------------------------


def test_a_generated_config_round_trips_to_the_defaults(tmp_path):
    schema = _schema()
    path = dump_config(tmp_path / "generated.yaml", schema)
    assert load_config(path, schema) == schema.validate({})


def test_a_generated_config_documents_every_setting(tmp_path):
    schema = _schema()
    text = dump_config(tmp_path / "generated.yaml", schema).read_text(encoding="utf-8")
    for setting in schema:
        assert f"{setting.name}:" in text, f"{setting.name} missing from generated config"
        assert setting.help in text, f"{setting.name} help missing from generated config"


def test_a_generated_config_records_units_choices_and_prerequisites(tmp_path):
    text = dump_config(tmp_path / "generated.yaml", _schema()).read_text(encoding="utf-8")
    assert "[um; range 0.0..]" in text
    assert "one of: fast, full" in text
    assert "needs use_masks" in text


def test_generating_with_values_writes_those_values(tmp_path):
    schema = _schema()
    path = dump_config(tmp_path / "generated.yaml", schema, values={"mode": "full"})
    assert load_config(path, schema)["mode"] == "full"


def test_generating_validates_the_values_it_is_given(tmp_path):
    with pytest.raises(ConfigError, match="allowed values are"):
        dump_config(tmp_path / "generated.yaml", _schema(), values={"mode": "medium"})


def test_a_generated_config_is_valid_yaml(tmp_path):
    text = dump_config(tmp_path / "generated.yaml", _schema()).read_text(encoding="utf-8")
    loaded = yaml.safe_load(text)
    assert loaded["output"]["diameters"] == {"B01": 5.0}


# --- command line ----------------------------------------------------------


def test_cli_flags_are_generated_from_the_schema():
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    parsed = parser.parse_args(["--voxel-size-um", "4", "--mode", "full"])
    assert cli_overrides(parsed) == {"voxel_size_um": "4", "mode": "full"}


def test_flags_not_given_are_absent_rather_than_defaulted():
    """"Not supplied" must stay distinguishable from "supplied the default"."""
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    assert cli_overrides(parser.parse_args([])) == {}


def test_choice_flags_reject_values_outside_the_schema(capsys):
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    with pytest.raises(SystemExit):
        parser.parse_args(["--mode", "medium"])


def test_bool_flags_take_an_explicit_true_or_false():
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    assert cli_overrides(parser.parse_args(["--use-masks", "true"]))["use_masks"] is True
    assert cli_overrides(parser.parse_args(["--use-masks", "no"]))["use_masks"] is False


def test_cli_overrides_flow_through_load_config(tmp_path):
    path = _write(tmp_path, "output:\n  mode: full\n")
    parser = argparse.ArgumentParser()
    add_schema_arguments(parser, _schema())
    parsed = parser.parse_args(["--mode", "fast", "--voxel-size-um", "2.5"])
    settings = load_config(path, _schema(), overrides=cli_overrides(parsed))
    assert settings["mode"] == "fast"
    assert settings["voxel_size_um"] == 2.5


# --- handing settings to a function ----------------------------------------


def test_settings_for_selects_the_named_subset():
    settings = _schema().validate({})
    assert settings_for(settings, ["mode", "use_masks"]) == {
        "mode": "fast",
        "use_masks": False,
    }


def test_settings_for_reports_names_that_are_not_present():
    with pytest.raises(ConfigError, match="Settings not present: nope"):
        settings_for(_schema().validate({}), ["mode", "nope"])
