"""Preprocessing: skeleton cleaning, bridging, skeletonization."""
from .skeleton import (
    SkeletonConnectivityStats,
    bridge_gaps,
    close_binary_mask,
    compute_skeleton_connectivity_stats,
    connect_skeleton_components,
    fill_binary_holes,
    inter_component_gap_distances,
    preprocess_skeleton_for_graph,
    skeletonize_voxel_bundles_into_paths,
    log_skeleton_connectivity_stats,
    skeletonize_volume,
    skeletonize_3d,
)
from .thick_vessels import (
    BRAID_FACTOR_LIMIT,
    THICK_VESSEL_MIN_RADIUS_UM,
    braid_factor,
    diagnose_mask_restriction_alignment,
    foreground_volume_um3,
    format_mask_restriction_alignment_report,
    inscribed_radius_map,
    lee_braid_factor,
    max_inscribed_radius_um,
    needs_thick_vessel_treatment,
    skeletonize_edt_ridge,
    skeletonize_thickness_gated,
    thick_vessel_object_mask,
    lee_sheet_excess,
)
from .thick_vessel_braid_guard import (
    BraidedThickVesselComponent,
    component_long_axis,
    detect_braided_thick_vessel_components,
    format_braided_thick_vessel_report,
)
from .skeleton_consistency import (
    diagnose_skeleton_mask_consistency,
    diagnose_vessels_missing_from_skeleton,
    format_skeleton_mask_consistency_report,
    format_vessels_missing_from_skeleton_report,
)
from .segmentation_cleanup import (
    clean_segmented_mask_for_skeletonisation,
    close_small_gaps,
    fill_enclosed_cavities,
    reconnect_vessel_like_components,
    remove_small_segmented_volumes,
    remove_surface_whiskers,
    smooth_vessel_surfaces,
    split_narrow_neck_components,
)
from .segmentation_quality import (
    SegmentationQualityScore,
    format_segmentation_quality_report,
    score_segmented_mask,
)
from .segmentation_raw_comparison import (
    SegmentationRawComparison,
    compare_segmentation_to_raw_image,
    format_segmentation_raw_comparison_report,
)

__all__ = [
    "BRAID_FACTOR_LIMIT",
    "THICK_VESSEL_MIN_RADIUS_UM",
    "SkeletonConnectivityStats",
    "braid_factor",
    "bridge_gaps",
    "close_binary_mask",
    "compute_skeleton_connectivity_stats",
    "connect_skeleton_components",
    "diagnose_mask_restriction_alignment",
    "fill_binary_holes",
    "foreground_volume_um3",
    "format_mask_restriction_alignment_report",
    "inscribed_radius_map",
    "inter_component_gap_distances",
    "lee_braid_factor",
    "lee_sheet_excess",
    "log_skeleton_connectivity_stats",
    "max_inscribed_radius_um",
    "needs_thick_vessel_treatment",
    "preprocess_skeleton_for_graph",
    "skeletonize_edt_ridge",
    "skeletonize_thickness_gated",
    "skeletonize_voxel_bundles_into_paths",
    "skeletonize_volume",
    "skeletonize_3d",  # deprecated alias
    "thick_vessel_object_mask",
    "BraidedThickVesselComponent",
    "component_long_axis",
    "detect_braided_thick_vessel_components",
    "format_braided_thick_vessel_report",
    "diagnose_skeleton_mask_consistency",
    "format_skeleton_mask_consistency_report",
    "diagnose_vessels_missing_from_skeleton",
    "format_vessels_missing_from_skeleton_report",
    "clean_segmented_mask_for_skeletonisation",
    "close_small_gaps",
    "fill_enclosed_cavities",
    "reconnect_vessel_like_components",
    "remove_small_segmented_volumes",
    "remove_surface_whiskers",
    "smooth_vessel_surfaces",
    "split_narrow_neck_components",
    "SegmentationQualityScore",
    "format_segmentation_quality_report",
    "score_segmented_mask",
    "SegmentationRawComparison",
    "compare_segmentation_to_raw_image",
    "format_segmentation_raw_comparison_report",
]
